# Generated by Django 3.2.5 on 2021-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.CharField(default=0, max_length=200, verbose_name='Pradžios laikas'),
            preserve_default=False,
        ),
    ]
