# Generated by Django 3.2.5 on 2021-07-15 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fightclub', '0002_alter_group_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(help_text='Pasirinkite vartotoją', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Narystės pavadinimas')),
                ('price', models.FloatField(verbose_name='Mėnesio kaina')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
