# Generated by Django 3.2.5 on 2021-07-15 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fightclub', '0003_auto_20210715_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='Aprašymas', help_text='Trumpas aprašymas', max_length=1000, verbose_name='Aprašymas'),
        ),
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(default='labas', max_length=1000, verbose_name='Aprašymas'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(help_text='Pasirinkite grupes', to='fightclub.Group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fightclub.membership')),
            ],
        ),
    ]
